### ISSUE TITLE
Portable版本在安装依赖库时报错

### ISSUE THREAD

**Issue by BoosterCore** [AIFSH/ComfyUI-IP_LAP#2]
报错信息如下：
`Building wheels for collected packages: lws
  Building wheel for lws (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'lws' extension
      creating build
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\lwslib
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ilwslib/ -IK:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\include -IK:\ComfyUI_windows_portable\python_embeded\include -IK:\ComfyUI_windows_portable\python_embeded\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tplws.bycython.cpp /Fobuild\temp.win-amd64-cpython-311\Release\lws.bycython.obj -O3
      cl: 命令行 warning D9002 :忽略未知选项“-O3”
      lws.bycython.cpp
      lws.bycython.cpp(196): fatal error C1083: 无法打开包括文件: “longintrepr.h”: No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lws
  Running setup.py clean for lws
Failed to build lws
ERROR: Could not build wheels for lws, which is required to install pyproject.toml-based projects`

**Comment by AIFSH** [comment]
没明白啥意思，啥是 portable 版本

**Comment by BoosterCore** [comment]
ComfyUI的官方portable版啊

**Comment by AIFSH** [comment]
还是下载一键包吧
【东哥视频翻译工作流Windows一键包来啦！-哔哩哔哩】 https://b23.tv/K1YFHkN

**Comment by BoosterCore** [comment]
嗯，后来查了很多资料，关键就是lws不兼容python3.11。
